// Copyright 2026, Stanislav Aleksandrov <lightofmysoul@gmail.com>
// SPDX-License-Identifier: BSL-1.0
// Author: Stanislav Aleksandrov <lightofmysoul@gmail.com>
// Note: Generated by ChatGPT 5.5 and Claude Opus 4.8.

#version 460
#extension GL_GOOGLE_include_directive : require

#define XRT_MESH_NLAYER_PASSTHROUGH 0
#include "mesh_nlayer_vert.inc.glsl"
