// Copyright 2026, Stanislav Aleksandrov <lightofmysoul@gmail.com>
// SPDX-License-Identifier: BSL-1.0
// Author: Stanislav Aleksandrov <lightofmysoul@gmail.com>
// Note: Generated by ChatGPT 5.5 and Claude Opus 4.8.

// Shared warp interface of the gfx N-layer fast path. Included by the
// mesh_nlayer vertex/fragment modules after mesh_nlayer.inc.glsl; the
// vertex stage defines WARP_STAGE_VERT and every includer defines
// XRT_MESH_NLAYER_PASSTHROUGH to 0 or 1 (the fused-camera variants).
// Declares the spec constants and the vertex->fragment interface both
// stages must agree on, plus the per-vertex warp implementation (glslang
// does not emit uncalled functions into the fragment module).
//
// All reprojection math runs per vertex; the fragment stage only keeps the
// non-linear tail (perspective divide, normalize, intersection, sampling).
// Everything from uv up to that tail is affine in uv, so interpolating the
// per-vertex results equals computing them per pixel; only an active
// begin/end scanout lerp leaves a (t x uv) cross term, sub-pixel at
// mesh-cell scale for real head-motion deltas.
//
// The interface is one spec-const-sized vec3 array holding only what this
// variant actually reads (locations cannot be spec constants, so separate
// exactly-sized arrays could not be packed back to back). Blocks, in order:
//
//   proj  [0, projection slots * warp_channels)
//         Per projection slot per channel: (x, y, w) of M(t) * pre_tan(uv).
//         The C side folds the [0, 1] remap and the sub-image rect into M,
//         so xy / w is the final source UV. Every projection slot has its
//         own elements: even without timewarp it needs its own source-FOV
//         mapping (M then holds a static transform), because one shared
//         mesh UV cannot represent several different submitted FOVs.
//   rays  Up to two shared unnormalized view-space ray sets per channel for
//         quad/cylinder/equirect2 slots: an uncompensated one and a
//         scanout-rotated one, selected per slot by
//         scanout_compensate_layers_mask. They sit at the tail bar the
//         passthrough element, uncompensated first, so both bases fold from
//         warp_count and the class-existence expressions below. The
//         fragment stage normalizes.
//   pt    [warp_count - 1]                 Passthrough camera source UV in
//         .xy and the validity margin in .z (negative = no camera coverage;
//         interpolation across a partially valid triangle fades the edge
//         out at the zero crossing). Exists only in the passthrough shader
//         variants when do_passthrough — always the very last element.
//
// warp_channels is 3 (r/g/b, chromatic aberration correction) or 1.
//
// Slot walks on both stages use a running element counter so every warp[]
// index folds to a constant once the layer loop unrolls at specialization.
// Do NOT hide the index behind a prefix-count helper: it is not folded
// before NIR lowers I/O derefs, and the resulting indirect varying access
// costs an order of magnitude in the multi-layer pipelines.

#ifdef WARP_STAGE_VERT
#define WARP_IO out
#else
#define WARP_IO in
#endif

// Whether the mesh UVs (the baked distortion LUT) are applied. When false the
// mesh is still rasterized — the per-vertex warp needs its tessellation — but
// with identity UVs derived from the vertex position.
layout(constant_id = 3) const bool do_distortion = true;
// Number of layers actually composited this draw; also sizes the fragment
// stage's sources array.
layout(constant_id = 4) const int layer_count = 1;
// Mirrors enum xrt_scanout_direction; selects the NDC axis the panel scans
// along. Canonically NONE iff nothing is scanout compensated: no slot, and
// no active passthrough (which compensates whenever the panel rolls), see
// the pipeline getter.
layout(constant_id = 5) const int scanout_direction = SCANOUT_TOP_TO_BOTTOM;
// Packed per-slot type vector, 2 bits per slot, see LAYER_TYPE_* in
// mesh_nlayer.inc.glsl. Spec constant so the per-slot dispatch constant-folds.
layout(constant_id = 6) const uint layer_types = 0;
// Whether to apply chromatic aberration correction. When false the
// green/geometric channel feeds the mono path.
layout(constant_id = 10) const bool do_cac = true;
// Total element count of the warp array, computed on the C side by
// render_gfx_nlayer_warp_count — the same call that gates the fast path
// against the device location budget. A bare spec constant rather than the
// obvious spec-const expression, because glslang only bounds-checks literal
// indices against a bare symbol's DEFAULT value (KhronosGroup/glslang#1783);
// the default has no runtime meaning. Id 11 is gfx-only; the other ids
// including the id 12 mask are shared with distortion_nlayer.comp.
layout(constant_id = 11) const int warp_count = 3;
// Bit i set = slot i gets NO scanout (begin -> end pose) compensation. A
// clear bit selects the begin/end matrix lerp for a projection slot and the
// scanout-rotated ray class for the rest. VIEW-space slots always have
// their bit set — they are locked to the device. The C side sets all bits
// when timewarp is off or the display is global flash, and the getter then
// folds scanout_direction to NONE (and vice versa).
layout(constant_id = 12) const uint scanout_compensate_layers_mask = 0;

#if XRT_MESH_NLAYER_PASSTHROUGH
// Fused camera background. These variants take a second descriptor set
// supplied by comp_passthrough. Gfx-only ids, far above the shared range so
// future shared ids can never collide.
layout(constant_id = 30) const bool do_passthrough = false;
#ifdef WARP_STAGE_VERT
// Apply the camera model (capture reprojection, curved window, forward KB4)
// when computing the camera UV; false passes the source UV straight through
// for a raw camera view and folds all of that code out of the variant.
layout(constant_id = 31) const bool do_camera_distortion = true;
#endif
const int warp_pt_count = do_passthrough ? 1 : 0;
// Whether the camera background is capture/scanout reprojected. The
// passthrough is world-locked by definition, so it takes no per-slot mask
// bit: it compensates whenever the variant compensates at all. The pipeline
// getter keeps scanout_direction from folding to NONE while a passthrough
// is active, so with timewarp on this stays live even when every app slot
// is uncompensated; with timewarp off the C side fills all four transforms
// identically and the folded static path matches.
const bool passthrough_reprojected = do_passthrough && scanout_direction != SCANOUT_NONE;
#else
const int warp_pt_count = 0;
#endif

layout(location = 0) WARP_IO vec3 warp[warp_count];

// Every access is guarded by the same spec constants that make its block
// exist, so no reachable index can exceed the specialized warp_count.
const int warp_channels = (do_distortion && do_cac) ? 3 : 1;

// Non-projection slots as one bit per slot: even-bit compaction of
// "2-bit type field != 0" (projection is type 0). All spec-constant
// expressions, so the ray-class layout folds before pipeline compilation.
const uint warp_nonproj_pairs = (layer_types | (layer_types >> 1)) & 0x55555555u;
const uint warp_nonproj_c1 = (warp_nonproj_pairs | (warp_nonproj_pairs >> 1)) & 0x33333333u;
const uint warp_nonproj_c2 = (warp_nonproj_c1 | (warp_nonproj_c1 >> 2)) & 0x0F0F0F0Fu;
const uint warp_nonproj_slots =
    ((warp_nonproj_c2 | (warp_nonproj_c2 >> 4)) & 0x00FF00FFu) & ((1u << layer_count) - 1u);

const bool warp_have_uncomp_rays = (warp_nonproj_slots & scanout_compensate_layers_mask) != 0u;
const bool warp_have_comp_rays = (warp_nonproj_slots & ~scanout_compensate_layers_mask) != 0u;
// An absent class's guarded accesses fold away, but they are still constant
// indices in the specialized module and Vulkan requires those to be in
// bounds even in dead code. Either base can go out of range when its class
// is absent (the passthrough-only variant's warp_count is smaller than
// warp_channels), so both alias element 0 instead.
const int warp_comp_ray_base = warp_have_comp_rays ? warp_count - warp_pt_count - warp_channels : 0;
const int warp_uncomp_ray_base =
    warp_have_uncomp_rays ? warp_count - warp_pt_count - warp_channels * (warp_have_comp_rays ? 2 : 1) : 0;
#if XRT_MESH_NLAYER_PASSTHROUGH
const int warp_pt_base = warp_count - 1;
#endif

// Folds to a literal per unrolled slot. Global-flash panels (SCANOUT_NONE)
// cannot compensate anything, so that case is hard-disabled regardless of
// the mask bits; both operands are spec constants, so this costs nothing.
bool slot_scanout_compensated(uint slot)
{
	if (scanout_direction == SCANOUT_NONE) {
		return false;
	}
	return ((scanout_compensate_layers_mask >> slot) & 1u) == 0u;
}

#ifdef WARP_STAGE_VERT

// Fraction of the frame's scanout that has passed when this vertex's row (or
// column) is lit. Takes post-vertex_rot NDC, so NDC y/x is the panel's scan
// axis. Affine in NDC, so the per-vertex value interpolates exactly.
float compute_scanout_fraction(vec2 ndc)
{
	if (scanout_direction == SCANOUT_TOP_TO_BOTTOM) {
		return ndc.y * 0.5 + 0.5;
	} else if (scanout_direction == SCANOUT_BOTTOM_TO_TOP) {
		return 0.5 - ndc.y * 0.5;
	} else if (scanout_direction == SCANOUT_LEFT_TO_RIGHT) {
		return ndc.x * 0.5 + 0.5;
	} else if (scanout_direction == SCANOUT_RIGHT_TO_LEFT) {
		return 0.5 - ndc.x * 0.5;
	}
	// SCANOUT_NONE: nothing consumes the value.
	return 0.0;
}

// Build the tan-angle vec4 (post-pre_transform, with OpenXR y-flip) for a
// single chroma channel.
vec4 build_pre_tan(vec2 uv, uint iz)
{
	vec4 pre = ubo.pre_transform[iz];
	vec4 v = vec4(uv * pre.zw + pre.xy, -1.0, 1.0);
	v.y = -v.y;
	return v;
}

// Begin/end matrix lerp for a scanout-compensated projection slot.
// Uncompensated slots read the begin matrix directly at the call site and
// have no end matrix. The SCANOUT_NONE branch is unreachable after the
// decode guard and folds away; kept as a safe default.
mat4 effective_timewarp_matrix(uint idx, float t)
{
	if (scanout_direction == SCANOUT_NONE) {
		return ubo.transform_timewarp_scanout_begin[idx];
	}
	mat4 tw_b = ubo.transform_timewarp_scanout_begin[idx];
	mat4 tw_e = ubo.transform_timewarp_scanout_end[idx];
	vec4 t4 = vec4(t);
	return mat4(fma(tw_e[0] - tw_b[0], t4, tw_b[0]),
	            fma(tw_e[1] - tw_b[1], t4, tw_b[1]),
	            fma(tw_e[2] - tw_b[2], t4, tw_b[2]),
	            fma(tw_e[3] - tw_b[3], t4, tw_b[3]));
}

// Per-row view-space rotation R_t = lerp(I, R_delta, t) for the compensated
// ray class. Identity for SCANOUT_NONE, where no compensated slot can exist.
mat3 effective_view_rotation(uint iz, float t)
{
	if (scanout_direction == SCANOUT_NONE) {
		return mat3(1.0);
	}
	mat3 R_delta = mat3(ubo.scanout_view_rot_delta[iz]);
	vec3 t3 = vec3(t);
	return mat3(fma(R_delta[0] - vec3(1.0, 0.0, 0.0), t3, vec3(1.0, 0.0, 0.0)),
	            fma(R_delta[1] - vec3(0.0, 1.0, 0.0), t3, vec3(0.0, 1.0, 0.0)),
	            fma(R_delta[2] - vec3(0.0, 0.0, 1.0), t3, vec3(0.0, 0.0, 1.0)));
}

// Unnormalized view-space ray for one channel; affine in uv, so it
// interpolates exactly. The fragment stage normalizes; the compensated ray
// class rotates the result at the call site.
vec3 build_view_ray_unnormalized(vec2 uv, uint iz)
{
	vec4 pre = ubo.pre_transform[iz];
	vec2 tan_xy = uv * pre.zw + pre.xy;
	return vec3(tan_xy.x, -tan_xy.y, -1.0);
}

// Write every element of the warp array for this vertex. The caller produces
// the per-channel source UVs (mesh attributes or identity); when !do_cac all
// three carry the same green/geometric value and only channel 0 exists.
void warp_emit(vec2 ruv, vec2 guv, vec2 buv, float scanout_t, uint iz)
{
	// Folds away when no projection slot exists.
	vec4 r_pre = build_pre_tan(ruv, iz);
	vec4 g_pre = build_pre_tan(guv, iz);
	vec4 b_pre = build_pre_tan(buv, iz);

	int out_elem = 0;
	for (int layer = 0; layer < layer_count; ++layer) {
		uint layer_u = uint(layer);
		uint slot_type = (layer_types >> (layer_u * 2u)) & 3u;
		if (slot_type != LAYER_TYPE_PROJECTION) {
			continue;
		}
		uint idx = layer_u * uint(VIEWS) + iz;
		mat4 m_eff;
		if (slot_scanout_compensated(layer_u)) {
			m_eff = effective_timewarp_matrix(idx, scanout_t);
		} else {
			m_eff = ubo.transform_timewarp_scanout_begin[idx];
		}
		warp[out_elem + 0] = (m_eff * r_pre).xyw;
		if (warp_channels == 3) {
			warp[out_elem + 1] = (m_eff * g_pre).xyw;
			warp[out_elem + 2] = (m_eff * b_pre).xyw;
		}
		out_elem += warp_channels;
	}

	if (warp_have_uncomp_rays) {
		warp[warp_uncomp_ray_base + 0] = build_view_ray_unnormalized(ruv, iz);
		if (warp_channels == 3) {
			warp[warp_uncomp_ray_base + 1] = build_view_ray_unnormalized(guv, iz);
			warp[warp_uncomp_ray_base + 2] = build_view_ray_unnormalized(buv, iz);
		}
	}

	if (warp_have_comp_rays) {
		mat3 view_rotation = effective_view_rotation(iz, scanout_t);
		warp[warp_comp_ray_base + 0] = view_rotation * build_view_ray_unnormalized(ruv, iz);
		if (warp_channels == 3) {
			warp[warp_comp_ray_base + 1] = view_rotation * build_view_ray_unnormalized(guv, iz);
			warp[warp_comp_ray_base + 2] = view_rotation * build_view_ray_unnormalized(buv, iz);
		}
	}
}

#if XRT_MESH_NLAYER_PASSTHROUGH

layout(set = 1, binding = 2, std430) readonly buffer PassthroughCurve
{
	float alpha[];
} passthrough_curve;

bool
apply_curved_window(uint iz, inout vec3 ray)
{
	PassthroughData data = ubo.passthrough[iz];
	vec3 axis = vec3(data.r0.w, data.r1.w, data.r2.w);
	ray = normalize(ray);
	float cosine = dot(ray, axis);
	const float minimum = 0.01;
	const float step = 0.99 / 999.0;
	if (cosine < minimum) {
		return false;
	}
	if (1.0 - cosine > step) {
		float position = (cosine - minimum) / step;
		int index = clamp(int(floor(position)), 0, 998);
		float fraction = position - float(index);
		int base = int(iz) * 1000;
		float alpha = mix(passthrough_curve.alpha[base + index],
		                  passthrough_curve.alpha[base + index + 1],
		                  fraction);
		ray += alpha * axis;
	}
	return ray.z > 1e-6;
}

bool
project_passthrough_at(uint iz,
                       vec2 output_uv,
                       float capture_fraction,
                       float scanout_fraction,
                       out vec2 source_uv,
                       out float valid_margin)
{
	PassthroughData data = ubo.passthrough[iz];
	vec4 pre = ubo.pre_transform[iz];
	vec2 tan_xy = output_uv * pre.zw + pre.xy;
	vec3 ray = vec3(tan_xy.x, -tan_xy.y, -1.0);

	mat4 eye_to_capture = data.transform_capture_begin_scanout_begin;
	if (passthrough_reprojected) {
		vec4 display_t = vec4(scanout_fraction);
		mat4 capture_begin =
		    mat4(fma(data.transform_capture_begin_scanout_end[0] -
		                 data.transform_capture_begin_scanout_begin[0],
		             display_t, data.transform_capture_begin_scanout_begin[0]),
		         fma(data.transform_capture_begin_scanout_end[1] -
		                 data.transform_capture_begin_scanout_begin[1],
		             display_t, data.transform_capture_begin_scanout_begin[1]),
		         fma(data.transform_capture_begin_scanout_end[2] -
		                 data.transform_capture_begin_scanout_begin[2],
		             display_t, data.transform_capture_begin_scanout_begin[2]),
		         fma(data.transform_capture_begin_scanout_end[3] -
		                 data.transform_capture_begin_scanout_begin[3],
		             display_t, data.transform_capture_begin_scanout_begin[3]));
		mat4 capture_end =
		    mat4(fma(data.transform_capture_end_scanout_end[0] -
		                 data.transform_capture_end_scanout_begin[0],
		             display_t, data.transform_capture_end_scanout_begin[0]),
		         fma(data.transform_capture_end_scanout_end[1] -
		                 data.transform_capture_end_scanout_begin[1],
		             display_t, data.transform_capture_end_scanout_begin[1]),
		         fma(data.transform_capture_end_scanout_end[2] -
		                 data.transform_capture_end_scanout_begin[2],
		             display_t, data.transform_capture_end_scanout_begin[2]),
		         fma(data.transform_capture_end_scanout_end[3] -
		                 data.transform_capture_end_scanout_begin[3],
		             display_t, data.transform_capture_end_scanout_begin[3]));
		vec4 capture_t = vec4(capture_fraction);
		eye_to_capture =
		    mat4(fma(capture_end[0] - capture_begin[0], capture_t, capture_begin[0]),
		         fma(capture_end[1] - capture_begin[1], capture_t, capture_begin[1]),
		         fma(capture_end[2] - capture_begin[2], capture_t, capture_begin[2]),
		         fma(capture_end[3] - capture_begin[3], capture_t, capture_begin[3]));
	}

	vec3 device_ray;
	if (data.misc.z > 0.0) {
		vec3 device_point = (eye_to_capture * vec4(ray * data.misc.z, 1.0)).xyz;
		device_ray = device_point - data.camera_position.xyz;
	} else {
		device_ray = (eye_to_capture * vec4(ray, 0.0)).xyz;
	}

	vec3 camera_ray = vec3(dot(data.r0.xyz, device_ray),
	                       dot(data.r1.xyz, device_ray),
	                       dot(data.r2.xyz, device_ray));
	if (camera_ray.z <= 1e-6 || !apply_curved_window(iz, camera_ray)) {
		return false;
	}

	vec2 normalized = camera_ray.xy / camera_ray.z -
	                  vec2(data.misc.w, data.camera_position.w);
	float radius = length(normalized);
	float theta = atan(radius);
	float theta2 = theta * theta;
	float distorted =
	    theta * (1.0 + theta2 * (data.dist.x +
	                             theta2 * (data.dist.y +
	                                       theta2 * (data.dist.z +
	                                                 theta2 * data.dist.w))));
	vec2 direction = radius > 1e-9 ? normalized / radius : vec2(0.0);
	source_uv = data.intr.xy * distorted * direction + data.intr.zw;

	float undistorted_margin = 1.0 - radius / data.misc.x;
	float distorted_margin = 1.0 - distorted / data.misc.y;
	vec2 low_margin = 2.0 * source_uv;
	vec2 high_margin = 2.0 * (vec2(1.0) - source_uv);
	valid_margin =
	    min(min(undistorted_margin, distorted_margin),
	        min(min(low_margin.x, low_margin.y),
	            min(high_margin.x, high_margin.y)));
	return true;
}

bool
project_passthrough(uint iz,
                    vec2 output_uv,
                    float scanout_fraction,
                    out vec2 source_uv,
                    out float valid_margin)
{
	if (!passthrough_reprojected) {
		return project_passthrough_at(iz, output_uv, 0.0, 0.0, source_uv, valid_margin);
	}

	/*
	 * The capture time depends on the camera row, which is itself the
	 * result of projection. Estimate it at mid-readout, then project once
	 * more using the resulting source row.
	 */
	vec2 estimated_uv;
	float estimated_margin;
	if (!project_passthrough_at(iz, output_uv, 0.5, scanout_fraction, estimated_uv, estimated_margin)) {
		return false;
	}
	float capture_fraction = clamp(estimated_uv.y, 0.0, 1.0);
	return project_passthrough_at(iz, output_uv, capture_fraction, scanout_fraction, source_uv, valid_margin);
}

// Write the passthrough element: the per-vertex camera projection of the
// warp stage. Takes the green/geometric display UV — the same distortion
// the app layers get — so the camera background lands at the correct
// angular position. Nothing to write when this variant carries no
// passthrough (the element does not exist, see warp_pt_count).
void passthrough_emit(vec2 geo_uv, float scanout_t, uint iz)
{
	if (!do_passthrough) {
		return;
	}

	vec2 source_uv = vec2(0.0);
	float valid_margin = -1.0;
	if (!do_camera_distortion) {
		source_uv = geo_uv;
		valid_margin = 1.0;
	} else if (!project_passthrough(iz, geo_uv, scanout_t, source_uv, valid_margin)) {
		source_uv = vec2(0.0);
		valid_margin = -1.0;
	}
	warp[warp_pt_base] = vec3(source_uv, valid_margin);
}

#endif // XRT_MESH_NLAYER_PASSTHROUGH

#endif // WARP_STAGE_VERT
