// Copyright 2026, Stanislav Aleksandrov <lightofmysoul@gmail.com>
// SPDX-License-Identifier: BSL-1.0
// Author: Stanislav Aleksandrov <lightofmysoul@gmail.com>
// Note: Generated by ChatGPT 5.5 and Claude Opus 4.8.

// Shared interface of the gfx N-layer fast path (mesh_nlayer.vert +
// mesh_nlayer.frag): one draw per view composites
// every layer inside a single fragment shader, mirroring distortion_nlayer.comp.
// The UBO carries both views' data; the push constant selects the view for the
// current draw (the gfx stand-in for the compute shader's gl_GlobalInvocationID.z).

#define VIEWS 2
#define MAX_NLAYER 8

// Mirrors enum xrt_scanout_direction in xrt_defines.h. Today only NONE
// (single-matrix; global-flash panels) and TOP_TO_BOTTOM (per-row begin/end
// lerp; rolling-shutter panels) are produced by the C side.
#define SCANOUT_NONE          0
#define SCANOUT_TOP_TO_BOTTOM 1
#define SCANOUT_BOTTOM_TO_TOP 2
#define SCANOUT_LEFT_TO_RIGHT 3
#define SCANOUT_RIGHT_TO_LEFT 4

// Per-slot layer type as packed in the layer_types spec constant, 2 bits per
// slot. Consumed by both mesh_nlayer_warp.inc.glsl and mesh_nlayer.frag.
#define LAYER_TYPE_PROJECTION 0u
#define LAYER_TYPE_QUAD       1u
#define LAYER_TYPE_CYLINDER   2u
#define LAYER_TYPE_EQUIRECT2  3u

// Same layout as distortion_nlayer.comp's QuadData; see there for field docs.
struct QuadData
{
	vec3 position;
	float _pad0;
	vec3 normal;
	float _pad1;
	mat4 inverse_transform;
	vec2 extent;
	vec2 _pad2;
};

// Same layout as distortion_nlayer.comp's WrapData; see there for field docs.
struct WrapData
{
	mat4 mv_inverse;
	vec4 params;
};

#if XRT_MESH_NLAYER_PASSTHROUGH
// EFS curved-window + KB4 camera model, filled per view by comp_passthrough.
struct PassthroughData
{
	vec4 r0;
	vec4 r1;
	vec4 r2;
	vec4 intr;
	vec4 dist;
	vec4 misc;
	vec4 camera_position;
	mat4 transform_capture_begin_scanout_begin;
	mat4 transform_capture_begin_scanout_end;
	mat4 transform_capture_end_scanout_begin;
	mat4 transform_capture_end_scanout_end;
};
#endif

// Must match struct render_gfx_mesh_nlayer_ubo_data on the C side. Compared
// to distortion_nlayer.comp's Config: views[] (target offsets/extents) is
// dropped — the viewport does that — and vertex_rot[] is added for the vertex
// stage. Everything else is identical; per-(layer, view) arrays are
// flat-indexed as [layer * VIEWS + view]. A projection slot's begin matrix
// may hold a static source mapping, its end matrix is only filled for
// scanout-compensated slots, and its post_transform entry holds the
// bounds-test scale/bias (proj_uv_inside) instead of the sampling rect,
// which is folded into the matrices.
layout (binding = 1, std140) uniform restrict Config
{
	vec4 vertex_rot[VIEWS];
	vec4 pre_transform[VIEWS];
	mat4 scanout_view_rot_delta[VIEWS];
	vec4 post_transform[MAX_NLAYER * VIEWS];
	mat4 transform_timewarp_scanout_begin[MAX_NLAYER * VIEWS];
	mat4 transform_timewarp_scanout_end[MAX_NLAYER * VIEWS];
	QuadData quads[MAX_NLAYER * VIEWS];
	WrapData wraps[MAX_NLAYER * VIEWS];
#if XRT_MESH_NLAYER_PASSTHROUGH
	PassthroughData passthrough[VIEWS];
#endif
} ubo;

// View index of the current draw, dynamically uniform.
layout (push_constant) uniform Push
{
	uint view_index;
} pc;
