// Copyright 2026, Stanislav Aleksandrov <lightofmysoul@gmail.com>
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  AHRS-based IMU fusion using the xio Fusion library.
 * @author Stanislav Aleksandrov <lightofmysoul@gmail.com>
 * @note Generated by Claude Opus 4.6.
 * @ingroup aux_math
 */

#include "m_imu_xio_ahrs.h"

#include "FusionRemap.h"

#include <string.h>

#define NS_TO_S (1.0 / 1000000000.0)

void
m_imu_xio_ahrs_init(struct m_imu_xio_ahrs *ahrs, const struct m_imu_xio_ahrs_settings *settings)
{
	memset(ahrs, 0, sizeof(*ahrs));
	FusionAhrsInitialise(&ahrs->fusion);

	FusionAhrsSettings fs = {
	    .convention = FusionConventionNwu,
	    .gain = settings->gain,
	    .gyroscopeRange = settings->gyroscope_range,
	    .accelerationRejection = settings->acceleration_rejection,
	    .magneticRejection = settings->magnetic_rejection,
	    .recoveryTriggerPeriod = settings->recovery_trigger_period,
	};
	FusionAhrsSetSettings(&ahrs->fusion, &fs);

	ahrs->sensor_alignment = settings->sensor_alignment;
	ahrs->rot = (struct xrt_quat)XRT_QUAT_IDENTITY;
}

void
m_imu_xio_ahrs_reset(struct m_imu_xio_ahrs *ahrs)
{
	FusionAhrsReset(&ahrs->fusion);
	ahrs->rot = (struct xrt_quat)XRT_QUAT_IDENTITY;
	ahrs->last_timestamp_ns = 0;
	ahrs->initialized = false;
}

static float
m_imu_xio_ahrs_dt(struct m_imu_xio_ahrs *ahrs, uint64_t timestamp_ns)
{
	if (!ahrs->initialized) {
		ahrs->last_timestamp_ns = timestamp_ns;
		ahrs->initialized = true;
		return 0.0f;
	}

	float dt = (float)((double)(timestamp_ns - ahrs->last_timestamp_ns) * NS_TO_S);
	ahrs->last_timestamp_ns = timestamp_ns;

	if (dt <= 0.0f || dt > 1.0f) {
		return 0.0f;
	}

	return dt;
}

static void
m_imu_xio_ahrs_store_quat(struct m_imu_xio_ahrs *ahrs)
{
	// Remap quaternion from NWU (X=fwd, Y=left, Z=up) to OpenXR (X=right, Y=up, Z=back).
	FusionQuaternion q = FusionAhrsGetQuaternion(&ahrs->fusion);
	ahrs->rot = (struct xrt_quat){
	    .w = q.element.w,
	    .x = -q.element.y,
	    .y = q.element.z,
	    .z = -q.element.x,
	};
}

void
m_imu_xio_ahrs_update(struct m_imu_xio_ahrs *ahrs,
                      uint64_t timestamp_ns,
                      const struct xrt_vec3 *accel,
                      const struct xrt_vec3 *gyro)
{
	float dt = m_imu_xio_ahrs_dt(ahrs, timestamp_ns);
	if (dt == 0.0f) {
		return;
	}

	FusionVector g = FusionRemap((FusionVector){.axis = {gyro->x, gyro->y, gyro->z}}, ahrs->sensor_alignment);
	FusionVector a = FusionRemap((FusionVector){.axis = {accel->x, accel->y, accel->z}}, ahrs->sensor_alignment);

	FusionAhrsUpdateNoMagnetometer(&ahrs->fusion, g, a, dt);
	m_imu_xio_ahrs_store_quat(ahrs);
}

void
m_imu_xio_ahrs_update_mag(struct m_imu_xio_ahrs *ahrs,
                          uint64_t timestamp_ns,
                          const struct xrt_vec3 *accel,
                          const struct xrt_vec3 *gyro,
                          const struct xrt_vec3 *mag)
{
	float dt = m_imu_xio_ahrs_dt(ahrs, timestamp_ns);
	if (dt == 0.0f) {
		return;
	}

	FusionVector g = FusionRemap((FusionVector){.axis = {gyro->x, gyro->y, gyro->z}}, ahrs->sensor_alignment);
	FusionVector a = FusionRemap((FusionVector){.axis = {accel->x, accel->y, accel->z}}, ahrs->sensor_alignment);
	FusionVector m = FusionRemap((FusionVector){.axis = {mag->x, mag->y, mag->z}}, ahrs->sensor_alignment);

	FusionAhrsUpdate(&ahrs->fusion, g, a, m, dt);
	m_imu_xio_ahrs_store_quat(ahrs);
}

FusionAhrsFlags
m_imu_xio_ahrs_get_flags(const struct m_imu_xio_ahrs *ahrs)
{
	return FusionAhrsGetFlags(&ahrs->fusion);
}
