// Copyright 2026, Stanislav Aleksandrov <lightofmysoul@gmail.com>
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  AHRS-based IMU fusion using the xio Fusion library.
 * @author Stanislav Aleksandrov <lightofmysoul@gmail.com>
 * @note Generated by Claude Opus 4.6.
 * @ingroup aux_math
 */

#pragma once

#include "xrt/xrt_defines.h"

#include "FusionAhrs.h"
#include "FusionRemap.h"

#ifdef __cplusplus
extern "C" {
#endif

struct m_imu_xio_ahrs_settings
{
	//! Correction gain applied to accelerometer and magnetometer feedback.
	//! Higher values correct gyro drift faster but introduce more noise.
	//! 0 = pure gyro integration. Default: 0.5.
	float gain;

	//! Full-scale gyroscope range in degrees/sec.
	//! If any axis exceeds this, the AHRS resets (assumes sensor saturation).
	//! 0 = no limit. Default: 0.
	float gyroscope_range;

	//! Accelerometer rejection threshold in degrees.
	//! When accel-vs-gravity error exceeds this angle, accel feedback is
	//! ignored (e.g. during rapid movement). 0 = disable rejection. Default: 90.
	float acceleration_rejection;

	//! Magnetometer rejection threshold in degrees.
	//! When magnetic error exceeds this angle, mag feedback is ignored.
	//! 0 = disable rejection. Default: 90.
	float magnetic_rejection;

	//! Number of samples before forcing recovery from accel/mag rejection.
	//! 0 = never force recovery. Default: 0.
	unsigned int recovery_trigger_period;

	//! Sensor axis alignment relative to NWU body frame.
	//! Default assumes OpenXR convention (X=right, Y=up, Z=back).
	FusionRemapAlignment sensor_alignment;
};

#define M_IMU_XIO_AHRS_SETTINGS_DEFAULT                                                                                \
	{                                                                                                              \
	    .gain = 0.5f,                                                                                              \
	    .gyroscope_range = 0.0f,                                                                                   \
	    .acceleration_rejection = 90.0f,                                                                           \
	    .magnetic_rejection = 90.0f,                                                                               \
	    .recovery_trigger_period = 0,                                                                              \
	    .sensor_alignment = FusionRemapAlignmentNZNXPY,                                                            \
	}

struct m_imu_xio_ahrs
{
	FusionAhrs fusion;
	FusionRemapAlignment sensor_alignment;
	struct xrt_quat rot;
	uint64_t last_timestamp_ns;
	bool initialized;
};

/*!
 * Initialize the AHRS fusion.
 *
 * @param ahrs      AHRS state to initialize.
 * @param settings  Tuning parameters.
 */
void
m_imu_xio_ahrs_init(struct m_imu_xio_ahrs *ahrs, const struct m_imu_xio_ahrs_settings *settings);

/*!
 * Reset the AHRS fusion state.
 */
void
m_imu_xio_ahrs_reset(struct m_imu_xio_ahrs *ahrs);

/*!
 * Update the AHRS fusion with accelerometer and gyroscope data.
 *
 * @param ahrs          AHRS state.
 * @param timestamp_ns  Sample timestamp in nanoseconds.
 * @param accel         Accelerometer reading in g.
 * @param gyro          Gyroscope reading in degrees/sec.
 */
void
m_imu_xio_ahrs_update(struct m_imu_xio_ahrs *ahrs,
                      uint64_t timestamp_ns,
                      const struct xrt_vec3 *accel,
                      const struct xrt_vec3 *gyro);

/*!
 * Update the AHRS fusion with accelerometer, gyroscope, and magnetometer data.
 *
 * @param ahrs          AHRS state.
 * @param timestamp_ns  Sample timestamp in nanoseconds.
 * @param accel         Accelerometer reading in g.
 * @param gyro          Gyroscope reading in degrees/sec.
 * @param mag           Magnetometer reading in any calibrated units.
 */
void
m_imu_xio_ahrs_update_mag(struct m_imu_xio_ahrs *ahrs,
                          uint64_t timestamp_ns,
                          const struct xrt_vec3 *accel,
                          const struct xrt_vec3 *gyro,
                          const struct xrt_vec3 *mag);

/*!
 * Return the AHRS flags. The @p initialising flag indicates whether
 * the orientation estimate is still converging.
 */
FusionAhrsFlags
m_imu_xio_ahrs_get_flags(const struct m_imu_xio_ahrs *ahrs);

#ifdef __cplusplus
}
#endif
